spring:
  ai:
    mcp:
      server:
        name: spring-boot-ai-search-image-server
        version: 1.0.0
        type: SYNC
        stdio: false
  main:
    web-application-type: none
    banner-mode: off