server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: spring-boot-ai-mysql
  ai:
    openai:
      base-url: https://api.siliconflow.cn
      api-key: sk-111
      chat:
        options:
          model: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  datasource:
    mysql:
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&connectTimeout=5000&socketTimeout=60000&autoReconnect=true&failOverReadOnly=false&useSSL=false
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: abcd1234

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  global-config:
    banner: false
  type-aliases-package: com.cg.zz.domain

# springdoc-openapi config
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.cg.zz.controller
# knife4j config
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.advisor.SimpleChatAdvisor: DEBUG